/**
 * Represents a DTC definition document in the Firestore `dtc_definitions` collection.
 * Document ID is the normalized DTC code (e.g. "P1ABC").
 *
 * source breakdown:
 *   'local'        — seeded from a bundled dataset by an admin process
 *   'firebase'     — retrieved from Firestore (pre-verified community entry)
 *   'ai_generated' — generated by the AI backend; always reviewStatus:'pending_review'
 */
export interface DtcDefinition {
  code: string;
  title: string;
  severity: 'low' | 'medium' | 'high';
  description: string;
  commonCauses: string[];
  recommendedChecks: string[];
  safeToDrive: boolean;
  confidence: 'low' | 'medium' | 'high';
  source: 'local' | 'firebase' | 'ai_generated';
  reviewStatus: 'verified' | 'pending_review';
  createdAt: string;
  updatedAt: string;
}
