export interface DtcCode {
  code: string;
  title: string;
  description: string;
  category?: 'Powertrain' | 'Body' | 'Chassis' | 'Network' | 'Unknown';
  subsystem?: string;
  severity?: 'Low' | 'Medium' | 'High' | 'Critical' | 'Unknown';
  manufacturer?: string;
  possibleCauses?: string[];
  recommendedChecks?: string[];
  /**
   * 'generic' | 'manufacturer' — resolved from local bundled maps.
   * 'firebase' — retrieved from Firestore (pre-existing definition).
   * 'ai_generated' — generated by AI and saved to Firestore as pending_review.
   * 'unknown' — not found anywhere; displayed with fallback copy.
   */
  source: 'generic' | 'manufacturer' | 'firebase' | 'ai_generated' | 'unknown';
  // Fields populated only for firebase / ai_generated sources
  safeToDrive?: boolean;
  lookupConfidence?: 'low' | 'medium' | 'high';
  reviewStatus?: 'verified' | 'pending_review' | 'rejected' | 'needs_research';
}
