import { DtcCode } from './dtc-code.model';

export const GENERIC_DTC_MAP: Record<string, Omit<DtcCode, 'code' | 'source'>> = {
  P0100: {
    title: 'Mass Air Flow Sensor Circuit Malfunction',
    description: 'The MAF sensor signal is out of expected range.',
    category: 'Powertrain', subsystem: 'Fuel & Air Metering', severity: 'High',
    possibleCauses: ['Faulty MAF sensor', 'Dirty MAF sensor', 'Wiring fault'],
    recommendedChecks: ['Inspect MAF sensor connector', 'Clean or replace MAF sensor'],
  },
  P0101: {
    title: 'Mass Air Flow Sensor Range/Performance',
    description: 'MAF sensor output does not match expected values for current operating conditions.',
    category: 'Powertrain', subsystem: 'Fuel & Air Metering', severity: 'Medium',
    possibleCauses: ['Air leak after MAF sensor', 'Dirty MAF sensor', 'Faulty MAF sensor'],
    recommendedChecks: ['Check for intake air leaks', 'Clean MAF sensor'],
  },
  P0102: {
    title: 'Mass Air Flow Sensor Low Input',
    description: 'MAF sensor voltage or frequency is below minimum threshold.',
    category: 'Powertrain', subsystem: 'Fuel & Air Metering', severity: 'High',
    possibleCauses: ['Open circuit in MAF wiring', 'Faulty MAF sensor', 'Poor ground'],
    recommendedChecks: ['Check wiring and connectors', 'Test MAF sensor output voltage'],
  },
  P0103: {
    title: 'Mass Air Flow Sensor High Input',
    description: 'MAF sensor voltage or frequency is above maximum threshold.',
    category: 'Powertrain', subsystem: 'Fuel & Air Metering', severity: 'High',
    possibleCauses: ['Short to voltage in MAF wiring', 'Faulty MAF sensor'],
    recommendedChecks: ['Inspect MAF wiring for shorts', 'Replace MAF sensor if faulty'],
  },
  P0104: {
    title: 'Mass Air Flow Sensor Intermittent',
    description: 'MAF sensor signal is intermittently out of range.',
    category: 'Powertrain', subsystem: 'Fuel & Air Metering', severity: 'Medium',
    possibleCauses: ['Loose MAF connector', 'Damaged wiring harness'],
    recommendedChecks: ['Wiggle test wiring while monitoring live data', 'Inspect connector pins'],
  },
  P0110: {
    title: 'Intake Air Temperature Sensor Circuit Malfunction',
    description: 'IAT sensor circuit is outside acceptable operating range.',
    category: 'Powertrain', subsystem: 'Fuel & Air Metering', severity: 'Medium',
    possibleCauses: ['Faulty IAT sensor', 'Damaged wiring', 'Poor connector contact'],
    recommendedChecks: ['Check IAT sensor resistance vs temperature chart', 'Inspect wiring'],
  },
  P0115: {
    title: 'Engine Coolant Temperature Sensor Circuit Malfunction',
    description: 'ECT sensor circuit is open, shorted, or out of range.',
    category: 'Powertrain', subsystem: 'Engine Cooling', severity: 'High',
    possibleCauses: ['Faulty ECT sensor', 'Coolant leak affecting sensor', 'Wiring fault'],
    recommendedChecks: ['Check coolant level', 'Measure ECT sensor resistance', 'Inspect connector'],
  },
  P0120: {
    title: 'Throttle Position Sensor A Circuit Malfunction',
    description: 'TPS circuit voltage is outside acceptable limits.',
    category: 'Powertrain', subsystem: 'Throttle', severity: 'High',
    possibleCauses: ['Faulty TPS', 'Worn throttle body', 'Wiring fault'],
    recommendedChecks: ['Check TPS voltage at idle and WOT', 'Inspect throttle body for wear'],
  },
  P0130: {
    title: 'O2 Sensor Circuit Malfunction (Bank 1 Sensor 1)',
    description: 'Upstream oxygen sensor on Bank 1 circuit fault detected.',
    category: 'Powertrain', subsystem: 'Oxygen Sensor', severity: 'High',
    possibleCauses: ['Faulty O2 sensor', 'Exhaust leak before sensor', 'Wiring fault'],
    recommendedChecks: ['Check for exhaust leaks', 'Monitor O2 sensor live data', 'Test sensor heater circuit'],
  },
  P0133: {
    title: 'O2 Sensor Slow Response (Bank 1 Sensor 1)',
    description: 'Upstream O2 sensor on Bank 1 is responding too slowly to mixture changes.',
    category: 'Powertrain', subsystem: 'Oxygen Sensor', severity: 'Medium',
    possibleCauses: ['Aged or contaminated O2 sensor', 'Exhaust leak', 'Rich/lean condition masking response'],
    recommendedChecks: ['Check O2 sensor switching frequency', 'Inspect for exhaust leaks upstream'],
  },
  P0171: {
    title: 'System Too Lean (Bank 1)',
    description: 'Long-term fuel trim indicates a lean air/fuel mixture on Bank 1.',
    category: 'Powertrain', subsystem: 'Fuel Trim', severity: 'Medium',
    possibleCauses: ['Vacuum leak', 'Dirty or failing MAF sensor', 'Weak fuel pump', 'Clogged fuel injectors'],
    recommendedChecks: ['Check for vacuum leaks with smoke test', 'Inspect MAF sensor', 'Check fuel pressure'],
  },
  P0172: {
    title: 'System Too Rich (Bank 1)',
    description: 'Long-term fuel trim indicates a rich air/fuel mixture on Bank 1.',
    category: 'Powertrain', subsystem: 'Fuel Trim', severity: 'Medium',
    possibleCauses: ['Leaking fuel injector', 'High fuel pressure', 'Faulty coolant temp sensor causing over-fueling'],
    recommendedChecks: ['Check fuel pressure', 'Inspect injectors for leaks', 'Verify ECT sensor readings'],
  },
  P0300: {
    title: 'Random/Multiple Cylinder Misfire Detected',
    description: 'Misfires detected across multiple cylinders with no single cylinder dominant.',
    category: 'Powertrain', subsystem: 'Misfire', severity: 'High',
    possibleCauses: ['Worn spark plugs', 'Faulty ignition coils', 'Low fuel pressure', 'Vacuum leak'],
    recommendedChecks: ['Inspect spark plugs', 'Check ignition coil outputs', 'Check fuel pressure', 'Check for vacuum leaks'],
  },
  P0301: {
    title: 'Cylinder 1 Misfire Detected',
    description: 'Misfire detected on cylinder 1.',
    category: 'Powertrain', subsystem: 'Misfire', severity: 'High',
    possibleCauses: ['Faulty spark plug (cyl 1)', 'Bad ignition coil (cyl 1)', 'Fuel injector fault (cyl 1)'],
    recommendedChecks: ['Swap coil from another cylinder', 'Check spark plug condition', 'Perform compression test on cyl 1'],
  },
  P0302: {
    title: 'Cylinder 2 Misfire Detected',
    description: 'Misfire detected on cylinder 2.',
    category: 'Powertrain', subsystem: 'Misfire', severity: 'High',
    possibleCauses: ['Faulty spark plug (cyl 2)', 'Bad ignition coil (cyl 2)', 'Fuel injector fault (cyl 2)'],
    recommendedChecks: ['Swap coil from another cylinder', 'Check spark plug condition', 'Perform compression test on cyl 2'],
  },
  P0303: {
    title: 'Cylinder 3 Misfire Detected',
    description: 'Misfire detected on cylinder 3.',
    category: 'Powertrain', subsystem: 'Misfire', severity: 'High',
    possibleCauses: ['Faulty spark plug (cyl 3)', 'Bad ignition coil (cyl 3)', 'Fuel injector fault (cyl 3)'],
    recommendedChecks: ['Swap coil from another cylinder', 'Check spark plug condition', 'Perform compression test on cyl 3'],
  },
  P0304: {
    title: 'Cylinder 4 Misfire Detected',
    description: 'Misfire detected on cylinder 4.',
    category: 'Powertrain', subsystem: 'Misfire', severity: 'High',
    possibleCauses: ['Faulty spark plug (cyl 4)', 'Bad ignition coil (cyl 4)', 'Fuel injector fault (cyl 4)'],
    recommendedChecks: ['Swap coil from another cylinder', 'Check spark plug condition', 'Perform compression test on cyl 4'],
  },
  P0420: {
    title: 'Catalyst System Efficiency Below Threshold (Bank 1)',
    description: 'The catalytic converter on Bank 1 is not operating within efficiency limits.',
    category: 'Powertrain', subsystem: 'Catalyst', severity: 'Medium',
    possibleCauses: ['Worn or damaged catalytic converter', 'Oil or coolant burning contaminating catalyst', 'Faulty downstream O2 sensor'],
    recommendedChecks: ['Compare upstream and downstream O2 sensor waveforms', 'Check for oil/coolant burning', 'Inspect cat for damage'],
  },
  P0440: {
    title: 'Evaporative Emission Control System Malfunction',
    description: 'General fault in the EVAP system; leak or component failure detected.',
    category: 'Powertrain', subsystem: 'EVAP', severity: 'Low',
    possibleCauses: ['Loose or damaged gas cap', 'Faulty purge valve', 'Leak in EVAP hoses'],
    recommendedChecks: ['Check and tighten gas cap', 'Inspect EVAP hoses for cracks', 'Test purge valve operation'],
  },
  P0442: {
    title: 'Evaporative Emission Control System Small Leak Detected',
    description: 'A small leak (0.020" or less) has been detected in the EVAP system.',
    category: 'Powertrain', subsystem: 'EVAP', severity: 'Low',
    possibleCauses: ['Loose or damaged gas cap', 'Small crack in EVAP hose', 'Faulty vent or purge valve'],
    recommendedChecks: ['Inspect gas cap seal', 'Perform smoke test on EVAP system', 'Check vent valve'],
  },
  P0455: {
    title: 'Evaporative Emission Control System Large Leak Detected',
    description: 'A large leak has been detected in the EVAP system.',
    category: 'Powertrain', subsystem: 'EVAP', severity: 'Medium',
    possibleCauses: ['Missing or broken gas cap', 'Large crack or disconnected EVAP hose', 'Stuck-open purge valve'],
    recommendedChecks: ['Check gas cap', 'Inspect all EVAP lines', 'Test purge valve and vent valve'],
  },
};
